[tool.poetry]
name = "minecraft-server-check"
version = "0.1.0"
description = ""
authors = []
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
pystemd = "^0.13"
mcstatus = "^11.1"
dacite = "^1.8"
tenacity = "^8.3"
schedule = "^1.2"

[tool.poetry.scripts]
minecraft-server-check = "src.main:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
