permit_join: false
homeassistant:
  enabled: true
mqtt:
  base_topic: zigbee2mqtt
  server: mqtt://host.containers.internal:1883
  keepalive: 60
  password: "!secrets.yaml mqtt_password"
  reject_unauthorized: true
  user: "!secrets.yaml mqtt_user"
  version: 4
serial:
  port: /dev/ttyZigbee
  adapter: zstack
frontend:
  enabled: true
advanced:
  network_key: "!secrets.yaml network_key"
  log_level: info
  log_output:
    - console
  channel: 25
  last_seen: ISO_8601
devices:
  "0xa4c13844697d3aa2":
    friendly_name: hallway_wardrobe_led_controller_1
    homeassistant:
      name: Hallway Wardrobe LED Controller 1
  "0x00158d00091214d6":
    friendly_name: hallway_wardrobe_door_sensor_1
    homeassistant:
      name: Hallway Wardrobe Door Sensor 1
  "0x08ddebfffeace118":
    friendly_name: ldk_temperature_humidity_1
    homeassistant:
      name: LDK Temperature Humidity 1
  "0x08ddebfffeac702b":
    friendly_name: bedroom_temperature_humidity_1
    homeassistant:
      name: Bedroom Temperature Humidity 1
groups: {}
version: 4
