---
title: "Homer"
subtitle: "Server"
logo: "logo.png"

header: false
footer: false

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "// Home Automation"
    icon: "fa-solid fa-house-laptop"
    items:
      - name: "Home Assistant"
        logo: "{{ logo_base }}/home-assistant.png"
        url: "http://homeassistant.{{ domain }}/"
        target: "_blank"
      - name: "Zigbee2MQTT"
        logo: "{{ logo_base }}/zigbee2mqtt.png"
        url: "http://zigbee2mqtt.{{ domain }}/"
        target: "_blank"
      - name: "Node Red"
        logo: "{{ logo_base }}/node-red.png"
        url: "http://nodered.{{ domain }}/"
        target: "_blank"

  - name: "// Services"
    icon: "fa-solid fa-display"
    items:
      - name: "Immich"
        logo: "{{ logo_base }}/immich.png"
        url: "http://immich.{{ domain }}/"
        target: "_blank"
      - name: "Paperless"
        logo: "{{ logo_base }}/paperless-ngx.png"
        url: "http://paperless.{{ domain }}/"
        target: "_blank"
      - name: "Grist"
        logo: "{{ logo_base }}/grist.png"
        url: "http://grist.{{ domain }}/"
        target: "_blank"
      - name: "Maloja"
        logo: "{{ logo_base }}/maloja.png"
        url: "http://maloja.{{ domain }}/"
        target: "_blank"
      - name: "Multi Scrobbler"
        logo: "{{ logo_base }}/multi-scrobbler.png"
        url: "http://multi-scrobbler.{{ domain }}/"
        target: "_blank"

  - name: "// Server"
    icon: "fa-solid fa-server"
    items:
      - name: "Authentik"
        logo: "{{ logo_base }}/authentik.png"
        url: "http://authentik.{{ domain }}/"
        target: "_blank"
      - name: "Portainer"
        logo: "{{ logo_base }}/portainer.png"
        url: "http://portainer.{{ domain }}/"
        target: "_blank"
      - name: "WhatsUpDocker"
        logo: "{{ logo_base }}/whats-up-docker.png"
        url: "http://whatsupdocker.{{ domain }}/"
        target: "_blank"
      - name: "Netdata"
        logo: "{{ logo_base }}/netdata.png"
        url: "http://netdata.{{ domain }}/"
        target: "_blank"
      - name: "Traefik"
        logo: "{{ logo_base }}/traefik.png"
        url: "http://traefik.{{ domain }}/"
        target: "_blank"
