[__config__]
# This file doesn't have to exist, but the key must be defined
oldver = "oldver.json"
newver = "versions.json"


[authentik]
source = "container"
registry = "ghcr.io"
container = "goauthentik/server"
exclude_regex = ".*rc.*"

[authentik-postgres]
source = "container"
registry = "docker.io"
container = "library/postgres"
include_regex = "^\\d+\\.\\d+-alpine$"

[authentik-redis]
source = "container"
registry = "docker.io"
container = "library/redis"
include_regex = "\\d+\\.\\d+\\.\\d+-alpine"

[grist]
source = "container"
registry = "docker.io"
container = "gristlabs/grist"

[mosquitto]
source = "container"
registry = "docker.io"
container = "library/eclipse-mosquitto"

[zigbee2mqtt]
source = "container"
registry = "docker.io"
container = "koenkk/zigbee2mqtt"

[nodered]
source = "container"
registry = "docker.io"
container = "nodered/node-red"
include_regex = "\\d+\\.\\d+\\.\\d+"

[homeassistant-mariadb]
source = "container"
registry = "docker.io"
container = "library/mariadb"
exclude_regex = ".*rc.*"

[homeassistant]
source = "container"
registry = "docker.io"
container = "homeassistant/home-assistant"
include_regex = "\\d+\\.\\d+\\.\\d+"

[immich-server]
source = "container"
registry = "ghcr.io"
container = "immich-app/immich-server"
include_regex = "v\\d+\\.\\d+\\.\\d+"

[immich-machine-learning]
source = "container"
registry = "ghcr.io"
container = "immich-app/immich-machine-learning"
include_regex = "v\\d+\\.\\d+\\.\\d+"

[multi-scrobbler]
source = "container"
registry = "docker.io"
container = "foxxmd/multi-scrobbler"

[maloja]
source = "container"
registry = "docker.io"
container = "krateng/maloja"

[librechat-mongodb]
source = "container"
registry = "docker.io"
container = "library/mongo"
exclude_regex = ".*rc.*"

[librechat-server]
source = "container"
registry = "ghcr.io"
container = "danny-avila/librechat"

[librechat-rag]
source = "container"
registry = "ghcr.io"
container = "danny-avila/librechat-rag-api-dev-lite"

[librechat-vector]
source = "container"
registry = "docker.io"
container = "ankane/pgvector"

[paperless]
source = "container"
registry = "ghcr.io"
container = "paperless-ngx/paperless-ngx"

[portainer]
source = "container"
registry = "docker.io"
container = "portainer/portainer-ce"
include_regex = "\\d+\\.\\d+\\.\\d+-alpine"