[audiobookshelf]
digest = 'sha256:f60a19bb94a9fc763212be0116502b0c2cee1da655c9320137a3020fb1ed2dca'
image = 'advplyr/audiobookshelf'
registry = 'ghcr.io'
version = '2.27.0'
versioning = 'semver'

[authentik-postgresql]
digest = 'sha256:7c688148e5e156d0e86df7ba8ae5a05a2386aaec1e2ad8e6d11bdf10504b1fb7'
image = 'library/postgres'
registry = 'docker.io'
version = '16.9-alpine'
versioning = 'regex:^(?<major>16)\.(?<minor>\d+)-alpine$'

[authentik-redis]
digest = 'sha256:bb186d083732f669da90be8b0f975a37812b15e913465bb14d845db72a4e3e08'
image = 'library/redis'
registry = 'docker.io'
version = '7.4.5-alpine'
versioning = 'regex:^(?<major>7)\.(?<minor>\d+)\.(?<patch>\d+)-alpine$'

[authentik-server]
digest = 'sha256:acde6a1fc963301fe27f7e86facb9aefbc68eb523210bcab5679a899e6bf72d5'
image = 'goauthentik/server'
registry = 'ghcr.io'
version = '2025.6.4'
versioning = 'regex:^(?<major>\d{4})\.(?<minor>\d+)\.(?<patch>\d+)$'

[authentik-worker]
digest = 'sha256:acde6a1fc963301fe27f7e86facb9aefbc68eb523210bcab5679a899e6bf72d5'
image = 'goauthentik/server'
registry = 'ghcr.io'
version = '2025.6.4'
versioning = 'regex:^(?<major>\d{4})\.(?<minor>\d+)\.(?<patch>\d+)$'

[ente-museum]
digest = 'sha256:a157cd2afb7caea14438f79dfd3b78c6dc05bf5b61c1311e3e9e7cf0ad3d5bf8'
image = 'ente-io/server'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[ente-postgresql]
digest = 'sha256:1414298ea93186123a6dcf872f778ba3bd2347edcbd2f31aa7bb2d9814ff5393'
image = 'library/postgres'
registry = 'docker.io'
version = '15.13-alpine'
versioning = 'regex:^(?<major>15)\.(?<minor>\d+)-alpine$'

[ente-web]
digest = 'sha256:cfebce0dfdb52227aff2518408e06af77adcdd3ed8f4b98121c3a374d812ecae'
image = 'ente-io/web'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[gluetun]
digest = 'sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00'
image = 'qmcgaw/gluetun'
registry = 'docker.io'
version = 'v3.40.0'
versioning = 'semver'

[grist]
digest = 'sha256:be6d84c8919c48bdaa0a52abbb3c32ebed1db59e17d339124d21c4191681cfaf'
image = 'gristlabs/grist'
registry = 'docker.io'
version = '1.7.1'
versioning = 'semver'

[homeassistant]
digest = 'sha256:e5bf3905955081dc4aae3b3980870c43ce6d8ffb880b5447addb3b3ba00f7bc0'
image = 'homeassistant/home-assistant'
registry = 'docker.io'
version = '2025.7.4'
versioning = 'regex:^(?<major>\d{4})\.(?<minor>\d+)\.(?<patch>\d+)$'

[homeassistant-postgresql]
digest = 'sha256:7c688148e5e156d0e86df7ba8ae5a05a2386aaec1e2ad8e6d11bdf10504b1fb7'
image = 'library/postgres'
registry = 'docker.io'
version = '16.9-alpine'
versioning = 'regex:^(?<major>16)\.(?<minor>\d+)-alpine$'

[immich-machine-learning]
digest = 'sha256:ef517c041fa4a6a84a6c3c4f88a1124058e686c9c92bf09a973e7e60c3c3ea1e'
image = 'immich-app/immich-machine-learning'
registry = 'ghcr.io'
version = 'v1.137.3'
versioning = 'semver'

[immich-postgresql]
digest = 'sha256:834049bf4c4e253b2db658e3585ca16535e9b548cb69de1e2a0e3599da2fd5de'
image = 'immich-app/postgres'
registry = 'ghcr.io'
version = '14-vectorchord0.4.3-pgvectors0.3.0'
versioning = 'regex:^(?<major>14)-vectorchord(?<minor>0\.4\.\d+)'

[immich-server]
digest = 'sha256:e517f806457057d44695152a0af2dfa094225a7d85eb37f518925e68864c658d'
image = 'immich-app/immich-server'
registry = 'ghcr.io'
version = 'v1.137.3'
versioning = 'semver'

[immich-valkey]
digest = 'sha256:5b8f8c333bef895c925f56629d6ba90aea95a4f7391f62411e625267c600b19c'
image = 'valkey/valkey'
registry = 'docker.io'
version = '8.1.3-bookworm'
versioning = 'regex:^(?<major>8)\.(?<minor>\d+)\.(?<patch>\d+)-bookworm$'

[jellyfin]
digest = 'sha256:7ae36aab93ef9b6aaff02b37f8bb23df84bb2d7a3f6054ec8fc466072a648ce2'
image = 'jellyfin/jellyfin'
registry = 'docker.io'
version = '10.10.7'
versioning = 'semver'

[maloja]
digest = 'sha256:4ecea26058d2ca5168a8d53820279942d28f0606664cea6425f42371d5d88f95'
image = 'krateng/maloja'
registry = 'docker.io'
version = '3.2.4'
versioning = 'semver'

[mosquitto]
digest = 'sha256:d219d3a72847f3aed6a1d66975972d3b17f86e39e8f6f6b86b4088b879c1a2d6'
image = 'library/eclipse-mosquitto'
registry = 'docker.io'
version = '2.0.22'
versioning = 'semver'

[multiscrobbler]
digest = 'sha256:e9d8f2596b065f60d15150d8e43e5eb8ee8796c258589801a1090d69e5447a81'
image = 'foxxmd/multi-scrobbler'
registry = 'docker.io'
version = '0.9.10'
versioning = 'semver'

[paperless-postgresql]
digest = 'sha256:7c688148e5e156d0e86df7ba8ae5a05a2386aaec1e2ad8e6d11bdf10504b1fb7'
image = 'library/postgres'
registry = 'docker.io'
version = '16.9-alpine'
versioning = 'regex:^(?<major>16)\.(?<minor>\d+)-alpine$'

[paperless-redis]
digest = 'sha256:bb186d083732f669da90be8b0f975a37812b15e913465bb14d845db72a4e3e08'
image = 'library/redis'
registry = 'docker.io'
version = '7.4.5-alpine'
versioning = 'regex:^(?<major>7)\.(?<minor>\d+)\.(?<patch>\d+)-alpine$'

[paperless-server]
digest = 'sha256:ab72a0ab42a792228cdbe83342b99a48acd49f7890ae54b1ae8e04401fba24ee'
image = 'paperless-ngx/paperless-ngx'
registry = 'ghcr.io'
version = '2.17.1'
versioning = 'semver'

[prowlarr]
digest = 'sha256:25d21c04c7cc39a706217abb77bb60b283d9eaaf16acf539c930e3c797e21f25'
image = 'linuxserver/prowlarr'
registry = 'docker.io'
version = '1.37.0'
versioning = 'semver'


[qbittorrent]
digest = 'sha256:a755d9f116b787a0087fd89df77bbc485c363cb88cf0f71348e25c735e77779e'
image = 'linuxserver/qbittorrent'
registry = 'docker.io'
version = '5.1.2'
versioning = 'regex:^v?(?<major>5)\.(?<minor>\d+)\.(?<patch>\d+)?$'
# Looks like the versioning scheme was different in the past, because there are tags like 20.04.1, which with semver comparison would be considered newer than 5.1.2.

[radarr]
digest = 'sha256:ae89f05ad7023258730ed62f5fcca63aab1e27ee5adcca1edb55d716f7cef356'
image = 'linuxserver/radarr'
registry = 'docker.io'
version = '5.26.2'
versioning = 'semver'

[sabnzbd]
digest = 'sha256:daab928f819bf9bb71dc50831441cae9308cfd5d8cb447a568fbb6b5a1ae8931'
image = 'linuxserver/sabnzbd'
registry = 'docker.io'
version = '4.5.2'
versioning = 'semver'

[sonarr]
digest = 'sha256:c0836f49c20000e603170dc95d74c2527e690d50309977d94fc171eaa49351a4'
image = 'linuxserver/sonarr'
registry = 'docker.io'
version = '4.0.15'
versioning = 'semver'

[zigbee2mqtt]
digest = 'sha256:472f4f5ed5d4258056093ea5745bc0ada37628b667d7db4fb12c2ffea74b2703'
image = 'koenkk/zigbee2mqtt'
registry = 'docker.io'
version = '2.6.0'
versioning = 'semver'