[audiobookshelf]
digest = "sha256:fe2ec344b4881ee0fad5c1605e7069c993c218c103e8a57e467e381ee9eebcfb"
image = "advplyr/audiobookshelf"
registry = "ghcr.io"
version = "2.26.3"
versioning = "semver"

[authentik-postgresql]
digest = "sha256:7c688148e5e156d0e86df7ba8ae5a05a2386aaec1e2ad8e6d11bdf10504b1fb7"
image = "library/postgres"
registry = "docker.io"
version = "16.9-alpine"
versioning = "regex:^(?<major>16)\\.(?<minor>\\d+)-alpine$"

[authentik-redis]
digest = "sha256:bb186d083732f669da90be8b0f975a37812b15e913465bb14d845db72a4e3e08"
image = "library/redis"
registry = "docker.io"
version = "7.4.5-alpine"
versioning = "regex:^(?<major>7)\\.(?<minor>\\d+)\\.(?<patch>\\d+)-alpine$"

[authentik-server]
digest = "sha256:acde6a1fc963301fe27f7e86facb9aefbc68eb523210bcab5679a899e6bf72d5"
image = "goauthentik/server"
registry = "ghcr.io"
version = "2025.6.4"
versioning = "regex:^(?<major>\\d{4})\\.(?<minor>\\d+)\\.(?<patch>\\d+)$"

[authentik-worker]
digest = "sha256:acde6a1fc963301fe27f7e86facb9aefbc68eb523210bcab5679a899e6bf72d5"
image = "goauthentik/server"
registry = "ghcr.io"
version = "2025.6.4"
versioning = "regex:^(?<major>\\d{4})\\.(?<minor>\\d+)\\.(?<patch>\\d+)$"

[ente-museum]
digest = "sha256:a157cd2afb7caea14438f79dfd3b78c6dc05bf5b61c1311e3e9e7cf0ad3d5bf8"
image = "ente-io/server"
registry = "ghcr.io"
version = "latest"
versioning = "docker"

[ente-postgresql]
digest = "sha256:1414298ea93186123a6dcf872f778ba3bd2347edcbd2f31aa7bb2d9814ff5393"
image = "library/postgres"
registry = "docker.io"
version = "15.13-alpine"
versioning = "regex:^(?<major>15)\\.(?<minor>\\d+)-alpine$"

[ente-web]
digest = "sha256:0f995958ad807d91dbc5e33561a427f7d29544e958e53343a01641b3b202129b"
image = "ente-io/web"
registry = "ghcr.io"
version = "latest"
versioning = "docker"

[gluetun]
digest = "sha256:2b42bfa046757145a5155acece417b65b4443c8033fb88661a8e9dcf7fda5a00"
image = "qmcgaw/gluetun"
registry = "docker.io"
version = "v3.40.0"
versioning = "semver"

[grist]
digest = "sha256:be6d84c8919c48bdaa0a52abbb3c32ebed1db59e17d339124d21c4191681cfaf"
image = "gristlabs/grist"
registry = "docker.io"
version = "1.7.1"
versioning = "semver"

[homeassistant]
digest = "sha256:e5bf3905955081dc4aae3b3980870c43ce6d8ffb880b5447addb3b3ba00f7bc0"
image = "homeassistant/home-assistant"
registry = "docker.io"
version = "2025.7.4"
versioning = "regex:^(?<major>\\d{4})\\.(?<minor>\\d+)\\.(?<patch>\\d+)$"

[homeassistant-postgresql]
digest = "sha256:7c688148e5e156d0e86df7ba8ae5a05a2386aaec1e2ad8e6d11bdf10504b1fb7"
image = "library/postgres"
registry = "docker.io"
version = "16.9-alpine"
versioning = "regex:^(?<major>16)\\.(?<minor>\\d+)-alpine$"

[immich-machine-learning]
digest = "sha256:591a7aef2a9ae087beb5aa24901ecffd441c8dc85db2a5addc6e08f4dbcddee3"
image = "immich-app/immich-machine-learning"
registry = "ghcr.io"
version = "v1.137.1"
versioning = "semver"

[immich-postgresql]
digest = "sha256:834049bf4c4e253b2db658e3585ca16535e9b548cb69de1e2a0e3599da2fd5de"
image = "immich-app/postgres"
registry = "ghcr.io"
version = "14-vectorchord0.4.3-pgvectors0.3.0"
versioning = "regex:^(?<major>14)-vectorchord(?<minor>0\\.4\\.\\d+)"

[immich-server]
digest = "sha256:fc2516bcd3a9e76a68447049bd3a69b84b618670c7a3a1d409b7d20606b2761f"
image = "immich-app/immich-server"
registry = "ghcr.io"
version = "v1.137.1"
versioning = "semver"

[immich-valkey]
digest = "sha256:facc1d2c3462975c34e10fccb167bfa92b0e0dbd992fc282c29a61c3243afb11"
image = "valkey/valkey"
registry = "docker.io"
version = "8.1.3-bookworm"
versioning = "regex:^(?<major>8)\\.(?<minor>\\d+)\\.(?<patch>\\d+)-bookworm$"

[jellyfin]
digest = "sha256:7ae36aab93ef9b6aaff02b37f8bb23df84bb2d7a3f6054ec8fc466072a648ce2"
image = "jellyfin/jellyfin"
registry = "docker.io"
version = "10.10.7"
versioning = "semver"

[maloja]
digest = "sha256:4ecea26058d2ca5168a8d53820279942d28f0606664cea6425f42371d5d88f95"
image = "krateng/maloja"
registry = "docker.io"
version = "3.2.4"
versioning = "semver"

[mosquitto]
digest = "sha256:d219d3a72847f3aed6a1d66975972d3b17f86e39e8f6f6b86b4088b879c1a2d6"
image = "library/eclipse-mosquitto"
registry = "docker.io"
version = "2.0.22"
versioning = "semver"

[multiscrobbler]
digest = "sha256:f6d4481f8163d74657fad1a0d00aea3c3a8d005633c8935019c0f06e35b8ba39"
image = "foxxmd/multi-scrobbler"
registry = "docker.io"
version = "0.9.9"
versioning = "semver"

[paperless-postgresql]
digest = "sha256:7c688148e5e156d0e86df7ba8ae5a05a2386aaec1e2ad8e6d11bdf10504b1fb7"
image = "library/postgres"
registry = "docker.io"
version = "16.9-alpine"
versioning = "regex:^(?<major>16)\\.(?<minor>\\d+)-alpine$"

[paperless-redis]
digest = "sha256:bb186d083732f669da90be8b0f975a37812b15e913465bb14d845db72a4e3e08"
image = "library/redis"
registry = "docker.io"
version = "7.4.5-alpine"
versioning = "regex:^(?<major>7)\\.(?<minor>\\d+)\\.(?<patch>\\d+)-alpine$"

[paperless-server]
digest = "sha256:ab72a0ab42a792228cdbe83342b99a48acd49f7890ae54b1ae8e04401fba24ee"
image = "paperless-ngx/paperless-ngx"
registry = "ghcr.io"
version = "2.17.1"
versioning = "semver"

[prowlarr]
digest = "sha256:d2462d470891c70073e31d158657a9b247b317c90238c40534d8be8f98671057"
image = "linuxserver/prowlarr"
registry = "docker.io"
version = "1.37.0"
versioning = "semver"

[qbittorrent]
digest = "sha256:a755d9f116b787a0087fd89df77bbc485c363cb88cf0f71348e25c735e77779e"
image = "linuxserver/qbittorrent"
registry = "docker.io"
version = "5.1.2"
versioning = "regex:^v?(?<major>5)\\.(?<minor>\\d+)\\.(?<patch>\\d+)?$"

[radarr]
digest = "sha256:ae89f05ad7023258730ed62f5fcca63aab1e27ee5adcca1edb55d716f7cef356"
image = "linuxserver/radarr"
registry = "docker.io"
version = "5.26.2"
versioning = "semver"

[sabnzbd]
digest = "sha256:daab928f819bf9bb71dc50831441cae9308cfd5d8cb447a568fbb6b5a1ae8931"
image = "linuxserver/sabnzbd"
registry = "docker.io"
version = "4.5.2"
versioning = "semver"

[sonarr]
digest = "sha256:c0836f49c20000e603170dc95d74c2527e690d50309977d94fc171eaa49351a4"
image = "linuxserver/sonarr"
registry = "docker.io"
version = "4.0.15"
versioning = "regex:^v?(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)(?:\\.(?<build>\\d+))?$"

[zigbee2mqtt]
digest = "sha256:1e639d3144960f246dcecc21d993169fd6844b5817e939bca498b2abf2c23159"
image = "koenkk/zigbee2mqtt"
registry = "docker.io"
version = "2.5.1"
versioning = "semver"