[audiobookshelf]
image = "advplyr/audiobookshelf"
registry = "ghcr.io"
version = "2.26.3"
digest = ""
versioning = "semver"

[authentik-postgresql]
image = "library/postgres"
registry = "docker.io"
version = "16.9-alpine"
digest = ""
versioning = "regex:^(?<major>16)\\.(?<minor>\\d+)-alpine$"

[authentik-redis]
image = "library/redis"
registry = "docker.io"
version = "7.4.5-alpine"
digest = ""
versioning = "regex:^(?<major>7)\\.(?<minor>\\d+)\\.(?<patch>\\d+)-alpine$"

[authentik-server]
image = "goauthentik/server"
registry = "ghcr.io"
version = "2025.6.4"
digest = ""
versioning = "regex:^(?<major>\\d{4})\\.(?<minor>\\d+)\\.(?<patch>\\d+)$"

[authentik-worker]
image = "goauthentik/server"
registry = "ghcr.io"
version = "2025.6.4"
digest = ""
versioning = "regex:^(?<major>\\d{4})\\.(?<minor>\\d+)\\.(?<patch>\\d+)$"

[ente-postgresql]
image = "library/postgres"
registry = "docker.io"
version = "15.13-alpine"
digest = ""
versioning = "regex:^(?<major>15)\\.(?<minor>\\d+)-alpine$"

[ente-museum]
image = "ente-io/server"
registry = "ghcr.io"
version = "latest"
digest = ""
versioning = "docker"

[ente-web]
image = "ente-io/web"
registry = "ghcr.io"
version = "latest"
digest = ""
versioning = "docker"

[gluetun]
image = "qmcgaw/gluetun"
registry = "docker.io"
version = "v3.40.0"
digest = ""
versioning = "semver"

[grist]
image = "gristlabs/grist"
registry = "docker.io"
version = "1.7.1"
digest = ""
versioning = "semver"

[homeassistant]
image = "homeassistant/home-assistant"
registry = "docker.io"
version = "2025.7.4"
digest = ""
versioning = "regex:^(?<major>\\d{4})\\.(?<minor>\\d+)\\.(?<patch>\\d+)$"

[homeassistant-postgresql]
image = "library/postgres"
registry = "docker.io"
version = "16.9-alpine"
digest = ""
versioning = "regex:^(?<major>16)\\.(?<minor>\\d+)-alpine$"

[immich-machine-learning]
image = "immich-app/immich-machine-learning"
registry = "ghcr.io"
version = "v1.137.1"
digest = ""
versioning = "semver"

[immich-postgresql]
image = "immich-app/postgres"
registry = "ghcr.io"
version = "14-vectorchord0.4.3-pgvectors0.3.0"
digest = ""
versioning = "regex:^(?<major>14)-vectorchord(?<minor>0\\.4\\.\\d+)"

[immich-server]
image = "immich-app/immich-server"
registry = "ghcr.io"
version = "v1.137.1"
digest = ""
versioning = "semver"

[immich-valkey]
image = "valkey/valkey"
registry = "docker.io"
version = "8.1.3-bookworm"
digest = ""
versioning = "regex:^(?<major>8)\\.(?<minor>\\d+)\\.(?<patch>\\d+)-bookworm$"

[jellyfin]
image = "jellyfin/jellyfin"
registry = "docker.io"
version = "10.10.7"
digest = ""
versioning = "semver"

[maloja]
image = "krateng/maloja"
registry = "docker.io"
version = "3.2.4"
digest = ""
versioning = "semver"

[mosquitto]
image = "library/eclipse-mosquitto"
registry = "docker.io"
version = "2.0.22"
digest = ""
versioning = "semver"

[multiscrobbler]
image = "foxxmd/multi-scrobbler"
registry = "docker.io"
version = "0.9.9"
digest = ""
versioning = "semver"

[paperless-postgresql]
image = "library/postgres"
registry = "docker.io"
version = "16.9-alpine"
digest = ""
versioning = "regex:^(?<major>16)\\.(?<minor>\\d+)-alpine$"

[paperless-redis]
image = "library/redis"
registry = "docker.io"
version = "7.4.5-alpine"
digest = ""
versioning = "regex:^(?<major>7)\\.(?<minor>\\d+)\\.(?<patch>\\d+)-alpine$"

[paperless-server]
image = "paperless-ngx/paperless-ngx"
registry = "ghcr.io"
version = "2.17.1"
digest = ""
versioning = "semver"

[prowlarr]
image = "linuxserver/prowlarr"
registry = "docker.io"
version = "1.37.0"
digest = ""
versioning = "semver"

[qbittorrent]
image = "linuxserver/qbittorrent"
registry = "docker.io"
version = "5.1.2"
digest = ""
versioning = "regex:^v?(?<major>5)\\.(?<minor>\\d+)\\.(?<patch>\\d+)?$"

[radarr]
image = "linuxserver/radarr"
registry = "docker.io"
version = "5.26.2"
digest = ""
versioning = "semver"

[sabnzbd]
image = "linuxserver/sabnzbd"
registry = "docker.io"
version = "4.5.2"
digest = ""
versioning = "semver"

[sonarr]
image = "linuxserver/sonarr"
registry = "docker.io"
version = "4.0.15"
digest = ""
versioning = "regex:^v?(?<major>\\d+)\\.(?<minor>\\d+)\\.(?<patch>\\d+)(?:\\.(?<build>\\d+))?$"

[zigbee2mqtt]
image = "koenkk/zigbee2mqtt"
registry = "docker.io"
version = "2.5.1"
digest = ""
versioning = "semver"
