# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 10
  unit_system: metric

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

api:

# Text to speech
tts:
  - platform: google_translate

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

recorder:
  purge_keep_days: 60
  auto_purge: true
  db_url: !secret mariadb_url

http:
  server_port: 80
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.31.0.0/24 # traefik
    - 172.32.0.0/24 # tailscale

input_boolean:
  vacation_mode:
    name: Vacation Mode
    icon: mdi:palm-tree

smartir:

climate:
  - platform: smartir
    name: LDK AC
    unique_id: ldk_ac
    device_code: 17000
    controller_data: remote.broadlink_rm4c_mini_ldk_1
    temperature_sensor: sensor.tuya_temperature_ldk_1_temperature
    humidity_sensor: sensor.tuya_temperature_ldk_1_humidity
    #power_sensor: binary_sensor.ac_power
    #power_sensor_restore_state: true
  - platform: smartir
    name: Bedroom AC
    unique_id: bedroom_ac
    device_code: 17000
    controller_data: remote.broadlink_rm4_pro_bedroom_1
    temperature_sensor: sensor.tuya_temperature_bedroom_1_temperature
    humidity_sensor: sensor.tuya_temperature_bedroom_1_humidity
    #power_sensor: binary_sensor.ac_power
    #power_sensor_restore_state: true

lovelace:
  mode: storage
  dashboards:
    lovelace-minimalist-custom:
      mode: yaml
      title: Minimalist
      icon: mdi:view-dashboard-outline
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/ui-lovelace-custom.yaml
