name: Rewrite SSH → HTTPS git URLs
description: Rewrites git URLs from SSH to HTTPS with a token for
  authentication, to allow git operations in environments without SSH agent
inputs:
  token:
    required: false
    description:
      Github Access Token to use in the rewritten URLs. If not provided,
      it will rewrite to standard HTTPS URLs without authentication.

runs:
  using: composite
  steps:
    - name: Rewrite SSH → HTTPS git URLs
      shell: bash
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        git config --global url."https://github.com/".insteadOf "ssh://git@github.com/"

    - name: Setup credential helper for token authentication
      if: ${{ inputs.token }}
      shell: bash
      run: |
        git config --global credential.helper "store --file=$HOME/.git-credentials"
        echo "https://x-access-token:${{ inputs.token }}@github.com" > $HOME/.git-credentials
