# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cockpit-files = {
    pname = "cockpit-files";
    version = "20";
    src = fetchurl {
      url = "https://github.com/cockpit-project/cockpit-files/releases/download/20/cockpit-files-20.tar.xz";
      sha256 = "sha256-5IABiavYKJvOR7OjpvTR/H2KZTVJzmsRMtJYHC6Gy80=";
    };
  };
  cockpit-podman = {
    pname = "cockpit-podman";
    version = "105";
    src = fetchurl {
      url = "https://github.com/cockpit-project/cockpit-podman/releases/download/105/cockpit-podman-105.tar.xz";
      sha256 = "sha256-XCx+xLtyo7srPFtXzyq54ynrcblYYA9lVASEHRka/XE=";
    };
  };
}
