[tool.poetry]
name = "renderer"
version = "0.1.0"
description = ""
authors = []
packages = [{ include = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
Jinja2 = "^3.1"

[tool.poetry.scripts]
renderer = "src.renderer:main"

[tool.poetry.group.dev.dependencies]
ruff = "^0.5.6"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"


[tool.ruff]
target-version = "py311"
line-length = 140

[tool.ruff.lint]
# Enable isort
extend-select = ["I"]