---
title: "Homer"
subtitle: "Server"
logo: "logo.png"

header: false
footer: false

stylesheet:
  - "assets/custom.css"

columns: "3" # You can change this to any number that is a factor of 12: (1, 2, 3, 4, 6, 12)
theme: default
colors:
  light:
    highlight-primary: "#fff5f2"
    highlight-secondary: "#fff5f2"
    highlight-hover: "#bebebe"
    background: "#12152B"
    card-background: "rgba(255, 245, 242, 0.8)"
    text: "#ffffff"
    text-header: "#fafafa"
    text-title: "#000000"
    text-subtitle: "#111111"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#3273dc"
    link-hover: "#2e4053"
    background-image: "../assets/wallpaper-light.jpeg" # Change wallpaper.jpeg to the name of your own custom wallpaper!
  dark:
    highlight-primary: "#181C3A"
    highlight-secondary: "#181C3A"
    highlight-hover: "#1F2347"
    background: "#12152B"
    card-background: "rgba(24, 28, 58, 0.8)"
    text: "#eaeaea"
    text-header: "#7C71DD"
    text-title: "#fafafa"
    text-subtitle: "#8B8D9C"
    card-shadow: rgba(0, 0, 0, 0.5)
    link: "#c1c1c1"
    link-hover: "#fafafa"
    background-image: "../assets/wallpaper.jpeg"

services:
  - name: "// Home Automation"
    icon: "fa-solid fa-house-laptop"
    items:
      - name: "Home Assistant"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/home-assistant.png"
        url: "http://homeassistant.{{ domain }}"
        target: "_blank"
      - name: "Zigbee2MQTT"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/zigbee2mqtt.png"
        url: "http://zigbee2mqtt.{{ domain }}"
        target: "_blank"
      - name: "Node Red"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/node-red.png"
        url: "http://nodered.{{ domain }}"
        target: "_blank"

  - name: "// Services"
    icon: "fa-solid fa-display"
    items:
      - name: "Immich"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/immich.png"
        url: "http://immich.{{ domain }}"
        target: "_blank"
      # - name: "Trilium"
      #   logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/trilium.png"
      #   url: "http://trilium.{{ domain }}"
      #   target: "_blank"

  - name: "// Server"
    icon: "fa-solid fa-server"
    items:
      - name: "Authentik"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/authentik.png"
        url: "http://authentik.{{ domain }}"
        target: "_blank"
      - name: "Portainer"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/portainer.png"
        url: "http://portainer.{{ domain }}"
        target: "_blank"
      - name: "WhatsUpDocker"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/whats-up-docker.png"
        url: "http://whatsupdocker.{{ domain }}"
        target: "_blank"
      - name: "Netdata"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/netdata.png"
        url: "http://netdata.{{ domain }}"
        target: "_blank"
      - name: "Traefik"
        logo: "https://cdn.jsdelivr.net/gh/walkxcode/dashboard-icons/png/traefik.png"
        url: "http://traefik.{{ domain }}"
        target: "_blank"
