[airtrail-server]
digest = 'sha256:9f702b91e0e7874d3c48a245dc10b9d1f726e2c1582d62237905ad905e5c35eb'
image = 'johly/airtrail'
registry = 'docker.io'
version = 'v3.11.1'
versioning = 'semver'

[airtrail-postgresql]
digest = 'sha256:9a8afca54e7861fd90fab5fdf4c42477a6b1cb7d293595148e674e0a3181de15'
image = 'library/postgres'
registry = 'docker.io'
version = '18.4-alpine'
versioning = 'docker'

[audiobookshelf]
digest = 'sha256:1eef6716183c52abafe5405e7d6be8390248ecd59c7488c44af871757ac8fc4d'
image = 'advplyr/audiobookshelf'
registry = 'ghcr.io'
version = '2.35.1'
versioning = 'semver'

[gitea-mirror]
digest = 'sha256:ef101da58f0e8d4e1eab96e37ef8f90cf756a8c6d68ab977f8ce7e4b69cb1318'
image = 'raylabshq/gitea-mirror'
registry = 'ghcr.io'
version = 'v3.21.0'
versioning = 'semver'

[gluetun]
digest = 'sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab'
image = 'qmcgaw/gluetun'
registry = 'docker.io'
version = 'v3.41.1'
versioning = 'semver'

[grist]
digest = 'sha256:d93db4640aeef1b2c3a1375b315798e72c591c98587a0a68c67286162a39a8ff'
image = 'gristlabs/grist'
registry = 'docker.io'
version = '1.7.16'
versioning = 'semver'

[homeassistant]
digest = 'sha256:1476924357b46e80735c13e94232ba5c853cac052e9df4bb28d50fa56348097b'
image = 'homeassistant/home-assistant'
registry = 'docker.io'
version = '2026.7.2'
versioning = 'regex:^(?<major>\d{4})\.(?<minor>\d+)\.(?<patch>\d+)$'

[homeassistant-postgresql]
digest = 'sha256:9a8afca54e7861fd90fab5fdf4c42477a6b1cb7d293595148e674e0a3181de15'
image = 'library/postgres'
registry = 'docker.io'
version = '18.4-alpine'
versioning = 'docker'

[immich-machine-learning]
digest = 'sha256:d76fe88b69282c09a97eac4f82dafa82cfd77bce274bc742591cde974f87dacb'
image = 'immich-app/immich-machine-learning'
registry = 'ghcr.io'
version = 'v3.0.3'
versioning = 'semver'

[immich-postgresql]
digest = 'sha256:87c050465fb969a68c7ac23e375e21f4c95cfacd0edce5fa1bc31e63b7891891'
image = 'immich-app/postgres'
registry = 'ghcr.io'
version = '14-vectorchord0.4.3-pgvectors0.3.0'
versioning = 'regex:^(?<major>14)-vectorchord(?<minor>0\.4\.\d+)'

[immich-server]
digest = 'sha256:c716dc20f957aafd89fa9d284a2ec63e25c9e2d8d8e87c6197d540a3dce237db'
image = 'immich-app/immich-server'
registry = 'ghcr.io'
version = 'v3.0.3'
versioning = 'semver'

[immich-valkey]
digest = 'sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571'
image = 'valkey/valkey'
registry = 'docker.io'
version = '8.1.3-bookworm'
versioning = 'regex:^(?<major>8)\.(?<minor>\d+)\.(?<patch>\d+)-bookworm$'

[koito]
digest = 'sha256:3011de405ba2a5c56270928c2b0391add8aa3b3ed68363531b3c64b61f238857'
image = 'gabehf/koito'
registry = 'docker.io'
version = 'v0.3.2'
versioning = 'semver'

[librechat-server]
digest = 'sha256:c5db3331b845e1f289f8d04c0c77936c4bbe372f76730a804abc1c37e44d23a9'
image = 'danny-avila/librechat'
registry = 'ghcr.io'
version = 'v0.8.7'
versioning = 'semver'

[librechat-mongodb]
digest = 'sha256:309d760ba3f7962e14d54ac6123c7fe72ed2d465196b4d0eaf8abcea7dd39450'
image = 'library/mongo'
registry = 'docker.io'
version = '8.3.4'
versioning = 'semver'

[librechat-rag]
digest = 'sha256:c0ad82657b556c1e16dcfca85d045788f67caa223e25e70eb687f4d16b41dedc'
image = 'danny-avila/librechat-rag-api-dev-lite'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[librechat-postgresql]
digest = 'sha256:da4ce21d3df8d2dcd313de387f169f43ae569a1fc50331bbffd3f55e3a65a0af'
image = 'pgvector/pgvector'
registry = 'docker.io'
version = '0.8.5-pg15-trixie'
versioning = 'regex:^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)-pg15-trixie$'

[maloja]
digest = 'sha256:4ecea26058d2ca5168a8d53820279942d28f0606664cea6425f42371d5d88f95'
image = 'krateng/maloja'
registry = 'docker.io'
version = '3.2.4'
versioning = 'semver'

[mousehole]
digest = 'sha256:2fc02b12362581e60bfd6adba788bda9eda93f8f31ed089581eeabcee4518b0d'
image = 'tmmrtn/mousehole'
registry = 'docker.io'
version = '0.5.0'
versioning = 'semver'

[multiscrobbler]
digest = 'sha256:aa8ec808fbeab9aecdfb5cbbe413e16578e995b883af2a5f94e8bfdf75c5fe43'
image = 'foxxmd/multi-scrobbler'
registry = 'ghcr.io'
version = 'edge'
versioning = 'docker'

[paperless-redis]
digest = 'sha256:9d317178eceac8454a2284a9e6df2466b93c745529947f0cd42a0fa9609d7005'
image = 'library/redis'
registry = 'docker.io'
version = '8.8.0-alpine'
versioning = 'docker'

[paperless-server]
digest = 'sha256:6c86cad803970ea782683a8e80e7403444c5bf3cf70de63b4d3c8e87500db92f'
image = 'paperless-ngx/paperless-ngx'
registry = 'ghcr.io'
version = '2.20.15'
versioning = 'semver'

[shelfmark]
digest = 'sha256:ff9ca442fbe782f90badcc166505a6929894f86f19c0d9bfb57bed70bef08bb6'
image = 'calibrain/shelfmark-lite'
registry = 'ghcr.io'
version = 'v1.3.3'
versioning = 'semver'

[qbittorrent]
digest = 'sha256:352371a7242e8b4aa10958ca02076d1023758070519b89a10251475fb9f1a35a'
image = 'linuxserver/qbittorrent'
registry = 'docker.io'
version = '5.2.3'
versioning = 'regex:^v?(?<major>5)\.(?<minor>\d+)\.(?<patch>\d+)?$'
# Looks like the versioning scheme was different in the past, because there are tags like 20.04.1, which with semver comparison would be considered newer than 5.1.2.

[searxng]
digest = 'sha256:3246b09eaf36b8031ea0cd54d7a217780d84d219d1e09040b6ebba72dcff52b7'
image = 'searxng/searxng'
registry = 'docker.io'
version = '2026.7.17-6913fba20'
versioning = 'regex:^(?<major>\d{4})\.(?<minor>\d{1,2})\.(?<patch>\d{1,2})-(?<build>[a-z0-9]+)$'

[trek]
digest = 'sha256:1abd6fc1fcb336aeb2be38552fb5f0a4fd9c3ef629b609a2dd99c8cc9954942b'
image = 'mauriceboe/trek'
registry = 'docker.io'
version = '3.3.0'
versioning = 'semver'
