[airtrail-server]
digest = 'sha256:b49918c441cd52ffd2ef795738e58031abbcfd1e8094a4365672282bb6b805b1'
image = 'johly/airtrail'
registry = 'docker.io'
version = 'v3.13.0'
versioning = 'semver'

[airtrail-postgresql]
digest = 'sha256:77f585114c32fbca283dc835b0596f4e52b51b4c6662d7810b2f4084f60a1873'
image = 'library/postgres'
registry = 'docker.io'
version = '18.6-alpine'
versioning = 'docker'

[audiobookshelf]
digest = 'sha256:581d68b2a6fc7ebf58d81c878a9f387cbbc0d88ac9d37b298b9cee10168af85b'
image = 'advplyr/audiobookshelf'
registry = 'ghcr.io'
version = '2.37.1'
versioning = 'semver'

[gitea-mirror]
digest = 'sha256:786b193599c60138a3fa04b8d7abc45faef9748af030d49da802c5a478314154'
image = 'raylabshq/gitea-mirror'
registry = 'ghcr.io'
version = 'v3.40.3'
versioning = 'semver'

[gluetun]
digest = 'sha256:fa19cc76b2af13d57a8d3dc3066f2ada061b1c761b8aecf989b3877c0486e027'
image = 'qmcgaw/gluetun'
registry = 'docker.io'
version = 'v3.41.3'
versioning = 'semver'

[grist]
digest = 'sha256:c862d4c1ffa2a36009d69b72e7ab319155c3529da7df2de0a4e437e994cfe7f1'
image = 'gristlabs/grist'
registry = 'docker.io'
version = '1.7.20'
versioning = 'semver'

[homeassistant]
digest = 'sha256:3e6710a7ab2a61311d9d899b719f6c3657791c63e8f4942cec4ebc42401d6b76'
image = 'homeassistant/home-assistant'
registry = 'docker.io'
version = '2026.9.4'
versioning = 'regex:^(?<major>\d{4})\.(?<minor>\d+)\.(?<patch>\d+)$'

[homeassistant-postgresql]
digest = 'sha256:77f585114c32fbca283dc835b0596f4e52b51b4c6662d7810b2f4084f60a1873'
image = 'library/postgres'
registry = 'docker.io'
version = '18.6-alpine'
versioning = 'docker'

[immich-machine-learning]
digest = 'sha256:f8b2869891c861a58dde969d86e7ea8a186e6059a55886632ee3249e51fb574a'
image = 'immich-app/immich-machine-learning'
registry = 'ghcr.io'
version = 'v3.2.0'
versioning = 'semver'

[immich-postgresql]
digest = 'sha256:87c050465fb969a68c7ac23e375e21f4c95cfacd0edce5fa1bc31e63b7891891'
image = 'immich-app/postgres'
registry = 'ghcr.io'
version = '14-vectorchord0.4.3-pgvectors0.3.0'
versioning = 'regex:^(?<major>14)-vectorchord(?<minor>0\.4\.\d+)'

[immich-server]
digest = 'sha256:d317916b28090c33eb36b308464ea391f8b7df1d850fcfea227a39ec879718c2'
image = 'immich-app/immich-server'
registry = 'ghcr.io'
version = 'v3.2.4'
versioning = 'semver'

[immich-valkey]
digest = 'sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571'
image = 'valkey/valkey'
registry = 'docker.io'
version = '8.1.3-bookworm'
versioning = 'regex:^(?<major>8)\.(?<minor>\d+)\.(?<patch>\d+)-bookworm$'

[koito]
digest = 'sha256:3011de405ba2a5c56270928c2b0391add8aa3b3ed68363531b3c64b61f238857'
image = 'gabehf/koito'
registry = 'docker.io'
version = 'v0.3.2'
versioning = 'semver'

[librechat-server]
digest = 'sha256:c5db3331b845e1f289f8d04c0c77936c4bbe372f76730a804abc1c37e44d23a9'
image = 'danny-avila/librechat'
registry = 'ghcr.io'
version = 'v0.8.7'
versioning = 'semver'

[librechat-mongodb]
digest = 'sha256:d731d77bfd7afd66bd487bdf627b5bf7ce4c3602ec461d635977021db529ebbc'
image = 'library/mongo'
registry = 'docker.io'
version = '8.3.11'
versioning = 'semver'

[librechat-rag]
digest = 'sha256:a62ce2221b43a9bb57fa6cb733e7047c80132960272c33d5704028f3071a1251'
image = 'danny-avila/librechat-rag-api-dev-lite'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[librechat-postgresql]
digest = 'sha256:8d4485d6fd3156d090ac5f37eb2e22eb59d93c91169414d5809414102ee924b9'
image = 'pgvector/pgvector'
registry = 'docker.io'
version = '0.8.7-pg15-trixie'
versioning = 'regex:^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)-pg15-trixie$'

[mousehole]
digest = 'sha256:2fc02b12362581e60bfd6adba788bda9eda93f8f31ed089581eeabcee4518b0d'
image = 'tmmrtn/mousehole'
registry = 'docker.io'
version = '0.5.0'
versioning = 'semver'

[multiscrobbler]
digest = 'sha256:449274cb8b5b855cc361056862aed6a11e5dcc0a72e2acb279ac78edf834a1c7'
image = 'foxxmd/multi-scrobbler'
registry = 'ghcr.io'
version = '0.19.2'
versioning = 'semver'

[shelfmark]
digest = 'sha256:edc889c12c4e54076432e5377b674fed4a1aaa934890f8a678bc5b38e5088a75'
image = 'calibrain/shelfmark-lite'
registry = 'ghcr.io'
version = 'v1.4.0'
versioning = 'semver'

[qbittorrent]
digest = 'sha256:b522f9f4b769f8f36d49d22d5eb6a92e9aa18904c6a1830b1439df511ec21983'
image = 'linuxserver/qbittorrent'
registry = 'docker.io'
version = '5.2.4'
versioning = 'regex:^v?(?<major>5)\.(?<minor>\d+)\.(?<patch>\d+)?$'
# Looks like the versioning scheme was different in the past, because there are tags like 20.04.1, which with semver comparison would be considered newer than 5.1.2.

[searxng]
digest = 'sha256:c642712fcedcdaa78fac44f71eada86aff510745826ba1bd1a368211fea2ce7f'
image = 'searxng/searxng'
registry = 'docker.io'
version = '2026.10.2-19ffbcd30'
versioning = 'regex:^(?<major>\d{4})\.(?<minor>\d{1,2})\.(?<patch>\d{1,2})-(?<build>[a-z0-9]+)$'

[trek]
digest = 'sha256:1ef1ccf41af8ae409e0435518facb5789b6adc99681ef26d1869508355455749'
image = 'mauriceboe/trek'
registry = 'docker.io'
version = '4.3.3'
versioning = 'semver'

[valheim-server]
digest = 'sha256:f3ccde9a4e292663cf5096d502ff33cc9617015f6d70b6a9ca0968543f165ef2'
image = 'community-valheim-tools/valheim-server'
registry = 'ghcr.io'
version = '1.4.0'
versioning = 'semver'
