[audiobookshelf]
digest = 'sha256:4143292c530f6ac6700afd13360c04f477e4f1a81c1c97c4224b1c7e4330c5c4'
image = 'advplyr/audiobookshelf'
registry = 'ghcr.io'
version = '2.34.0'
versioning = 'semver'

[ente-museum]
digest = 'sha256:4367349f3dd6b95eb6f05620fe8dd17f09845b3a913bec5e273caa9f950e4f9c'
image = 'ente-io/server'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[ente-postgresql]
digest = 'sha256:09e4f20b14ddb3dfe3a0c825b206032aaf8f28300ba2070c0b60fc1c10c6abc7'
image = 'library/postgres'
registry = 'docker.io'
version = '15.17-alpine'
versioning = 'regex:^(?<major>15)\.(?<minor>\d+)-alpine$'

[ente-web]
digest = 'sha256:848cdccdf7081b6c2f37f5233bb2a589d25df8b369359a5833fefd49306055f0'
image = 'ente-io/web'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[gitea-mirror]
digest = 'sha256:2d97c98fd6f32915bbcc247373b9b39606d337cb3fb576980673d842dcaea291'
image = 'raylabshq/gitea-mirror'
registry = 'ghcr.io'
version = 'v3.15.10'
versioning = 'semver'

[gluetun]
digest = 'sha256:1a5bf4b4820a879cdf8d93d7ef0d2d963af56670c9ebff8981860b6804ebc8ab'
image = 'qmcgaw/gluetun'
registry = 'docker.io'
version = 'v3.41.1'
versioning = 'semver'

[grist]
digest = 'sha256:006104fac45b6c59a05315f66dc37635ed11641b56519528ddf586bf0ed65e52'
image = 'gristlabs/grist'
registry = 'docker.io'
version = '1.7.13'
versioning = 'semver'

[homeassistant]
digest = 'sha256:d4fbec16196d5c8bedf32647f0ca7165f654d92a2e81f35a373508d3226cb867'
image = 'homeassistant/home-assistant'
registry = 'docker.io'
version = '2026.5.1'
versioning = 'regex:^(?<major>\d{4})\.(?<minor>\d+)\.(?<patch>\d+)$'

[homeassistant-postgresql]
digest = 'sha256:54451ecb8ab38c24c3ec123f2fd501303a3a1856a5c66e98cecf2460d5e1e9d7'
image = 'library/postgres'
registry = 'docker.io'
version = '18.3-alpine'
versioning = 'docker'

[immich-machine-learning]
digest = 'sha256:a2501141440f10516d329fdfba2c68082e19eb9ba6016c061ac80d23beadf7f3'
image = 'immich-app/immich-machine-learning'
registry = 'ghcr.io'
version = 'v2.7.5'
versioning = 'semver'

[immich-postgresql]
digest = 'sha256:87c050465fb969a68c7ac23e375e21f4c95cfacd0edce5fa1bc31e63b7891891'
image = 'immich-app/postgres'
registry = 'ghcr.io'
version = '14-vectorchord0.4.3-pgvectors0.3.0'
versioning = 'regex:^(?<major>14)-vectorchord(?<minor>0\.4\.\d+)'

[immich-server]
digest = 'sha256:c15bff75068effb03f4355997d03dc7e0fc58720c2b54ad6f7f10d1bc57efaa5'
image = 'immich-app/immich-server'
registry = 'ghcr.io'
version = 'v2.7.5'
versioning = 'semver'

[immich-valkey]
digest = 'sha256:fea8b3e67b15729d4bb70589eb03367bab9ad1ee89c876f54327fc7c6e618571'
image = 'valkey/valkey'
registry = 'docker.io'
version = '8.1.3-bookworm'
versioning = 'regex:^(?<major>8)\.(?<minor>\d+)\.(?<patch>\d+)-bookworm$'

[librechat-server]
digest = 'sha256:a46254938507971e0d4f7ed3f9d116bd9b118f4810b5b75eb716baf575645068'
image = 'danny-avila/librechat'
registry = 'ghcr.io'
version = 'v0.8.5'
versioning = 'semver'

[librechat-mongodb]
digest = 'sha256:94b405c5aa83d5160e6dd97383c4687d471f8a6bd247ed3ff6463c092ebf7a8c'
image = 'library/mongo'
registry = 'docker.io'
version = '8.3.2'
versioning = 'semver'

[librechat-rag]
digest = 'sha256:6dfb6832661ff9c26fa329c823ce266059e33567670a763e9ecb9b566b8daa68'
image = 'danny-avila/librechat-rag-api-dev-lite'
registry = 'ghcr.io'
version = 'latest'
versioning = 'docker'

[librechat-postgresql]
digest = 'sha256:73baaa709cd08ca631f516fa39949588ec5c82383d58746ea46aaf66cb1472a4'
image = 'pgvector/pgvector'
registry = 'docker.io'
version = '0.8.2-pg15-trixie'
versioning = 'regex:^(?<major>\d+)\.(?<minor>\d+)\.(?<patch>\d+)-pg15-trixie$'

[maloja]
digest = 'sha256:4ecea26058d2ca5168a8d53820279942d28f0606664cea6425f42371d5d88f95'
image = 'krateng/maloja'
registry = 'docker.io'
version = '3.2.4'
versioning = 'semver'

[mamapi]
digest = 'sha256:9403628e9c0e773c04bb640743105bdbfca53423033828e13d3f5efc79370493'
image = 'elforkhead/mamapi'
registry = 'ghcr.io'
version = 'v2.1.2'
versioning = 'semver'

[multiscrobbler]
digest = 'sha256:aecbf754a18c2ddc5d9bcf6385316a63aeae685f4106e76c25ab9d2c26c0f550'
image = 'foxxmd/multi-scrobbler'
registry = 'docker.io'
version = '0.13.3'
versioning = 'semver'

[paperless-redis]
digest = 'sha256:d146f83b1e0f02fc27c26a50cee39338c736674c5959db84363e6ae3cd9e02d2'
image = 'library/redis'
registry = 'docker.io'
version = '8.6.3-alpine'
versioning = 'docker'

[paperless-server]
digest = 'sha256:6c86cad803970ea782683a8e80e7403444c5bf3cf70de63b4d3c8e87500db92f'
image = 'paperless-ngx/paperless-ngx'
registry = 'ghcr.io'
version = '2.20.15'
versioning = 'semver'

[shelfmark]
digest = 'sha256:655168ef4dd1af939d368f9a8448bf2606888f8221b014f219a3a8eab1c4b307'
image = 'calibrain/shelfmark-lite'
registry = 'ghcr.io'
version = 'v1.3.0'
versioning = 'semver'

[qbittorrent]
digest = 'sha256:3679a75dd2304b695525d83a4ff14c458708b5da4a7ce53044240932139590e1'
image = 'linuxserver/qbittorrent'
registry = 'docker.io'
version = '5.1.4'
versioning = 'regex:^v?(?<major>5)\.(?<minor>\d+)\.(?<patch>\d+)?$'
# Looks like the versioning scheme was different in the past, because there are tags like 20.04.1, which with semver comparison would be considered newer than 5.1.2.

[sabnzbd]
digest = 'sha256:c65265edbfb42a1e4b6c68d3926e4aab4cf9cf185be1fafd1a692cb195cc9b0e'
image = 'linuxserver/sabnzbd'
registry = 'docker.io'
version = '5.0.1'
versioning = 'semver'

[searxng]
digest = 'sha256:6868f987196cc87a3535fd08d17a31589ecfb696ab94b894aa2d89477c9eda2e'
image = 'searxng/searxng'
registry = 'docker.io'
version = '2026.5.13-09829b1cc'
versioning = 'regex:^(?<major>\d{4})\.(?<minor>\d{1,2})\.(?<patch>\d{1,2})-(?<build>[a-z0-9]+)$'

[trek]
digest = 'sha256:79f88110b76980b261b81d1313ec82ee393149d97ae672e87a83e0b158e361a0'
image = 'mauriceboe/trek'
registry = 'docker.io'
version = '3.0.21'
versioning = 'semver'

[zigbee2mqtt]
digest = 'sha256:67c26dcf8346aced02fe1380a6afd1b57268bcef10faae3f6057c13d5d3dfa80'
image = 'koenkk/zigbee2mqtt'
registry = 'docker.io'
version = '2.10.1'
versioning = 'semver'
