[cockpit-files]
src.github = "cockpit-project/cockpit-files"
fetch.url = "https://github.com/cockpit-project/cockpit-files/releases/download/$ver/cockpit-files-$ver.tar.xz"

[cockpit-podman]
src.github = "cockpit-project/cockpit-podman"
fetch.url = "https://github.com/cockpit-project/cockpit-podman/releases/download/$ver/cockpit-podman-$ver.tar.xz"
