- platform: filter
  name: Bedroom temperature AVG
  unique_id: bedroom_temperature_avg
  entity_id: sensor.bedroom_temperature_humidity_1_temperature
  filters:
    - filter: outlier
      window_size: 10
    - filter: time_simple_moving_average
      window_size: "00:30"
      precision: 2

- platform: filter
  name: Bedroom humidity AVG
  unique_id: bedroom_humidity_avg
  entity_id: sensor.bedroom_temperature_humidity_1_humidity
  filters:
    - filter: outlier
      window_size: 10
    - filter: time_simple_moving_average
      window_size: "00:30"
      precision: 2

- platform: filter
  name: LDK temperature AVG
  unique_id: ldk_temperature_avg
  entity_id: sensor.ldk_temperature_humidity_1_temperature
  filters:
    - filter: outlier
      window_size: 10
    - filter: time_simple_moving_average
      window_size: "00:30"
      precision: 2

- platform: filter
  name: LDK humidity AVG
  unique_id: ldk_humidity_avg
  entity_id: sensor.ldk_temperature_humidity_1_humidity
  filters:
    - filter: outlier
      window_size: 10
    - filter: time_simple_moving_average
      window_size: "00:30"
      precision: 2
