- id: "1671356667944"
  alias: Set theme on startup
  description: ""
  trigger:
    - platform: homeassistant
      event: start
  condition: []
  action:
    - service: frontend.set_theme
      data:
        name: minimalist-desktop
  mode: single
