#SECTION - Core
# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 10
  unit_system: metric
  customize: !include_dir_merge_named configuration/customize/

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

# Enable integrations
api:
auth_header:
  debug: true
  username_header: X-Authentik-Username

logger:
  default: info
  logs:
    custom_components.auth_header: debug

recorder:
  purge_keep_days: 60
  auto_purge: true
  db_url: !secret db_url

http:
  server_port: 80
  use_x_forwarded_for: true
  trusted_proxies:
    - 172.31.0.0/24 #LINK - machines/geekomA5/modules/system/services/traefik/podman-traefik-network.nix

lovelace:
  mode: storage
  dashboards:
    lovelace-minimalist-grid:
      mode: yaml
      title: Minimalist Grid
      icon: mdi:view-dashboard-outline
      show_in_sidebar: true
      filename: ui_lovelace_minimalist/dashboard/ui-lovelace-custom-grid.yaml

#!SECTION - Core

# Includes
automation manual: !include_dir_merge_list automations/
automation ui: !include automations.yaml
input_boolean: !include_dir_merge_named configuration/input_boolean/
climate: !include_dir_merge_list configuration/climate/
sensor: !include_dir_merge_list configuration/sensors/
