# yaml-language-server: $schema=https://version-2024-2.goauthentik.io/blueprints/schema.json
version: 1
metadata:
  name: traefik-dashboard
  labels:
    blueprints.goauthentik.io/description: "Setup Traefik Dashboard Proxy Provider & Application"
entries:
  - model: authentik_providers_proxy.proxyprovider
    id: provider
    state: present
    identifiers:
      name: Traefik
    attrs:
      authentication_flow: !Find [authentik_flows.flow, [slug, default-authentication-flow]]
      authorization_flow: !Find [authentik_flows.flow, [slug, default-provider-authorization-implicit-consent]]
      mode: forward_single
      access_token_validity: {{ accessTokenValidity }}
      refresh_token_validity: {{ refreshTokenValidity }}
      external_host: http://traefik.{{ domain }}

  - model: authentik_core.application
    id: application
    state: present
    identifiers:
      name: Traefik
      slug: traefik
    attrs:
      provider: !KeyOf provider
      open_in_new_tab: true
      icon: {{ iconsProvider }}/traefik.png
      {{ groups.serverManagement | indent(6, False) }}

  - model: "authentik_policies.policybinding"
    identifiers:
      target: !KeyOf application
    attrs:
      group: !Find [authentik_core.group, [name, Server Admins]]
      enabled: true
      order: 0
