# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cockpit-files = {
    pname = "cockpit-files";
    version = "40";
    src = fetchurl {
      url = "https://github.com/cockpit-project/cockpit-files/releases/download/40/cockpit-files-40.tar.xz";
      sha256 = "sha256-Yp6s9x0Vu8Lgcg71aImTLJ8YNKJkfxhbSOcPckJVAGI=";
    };
  };
  cockpit-podman = {
    pname = "cockpit-podman";
    version = "125";
    src = fetchurl {
      url = "https://github.com/cockpit-project/cockpit-podman/releases/download/125/cockpit-podman-125.tar.xz";
      sha256 = "sha256-6XathPDmpJ4g3zn0pKoagsDNBQ+9o3iPd2nVs615esw=";
    };
  };
}
