# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cockpit-files = {
    pname = "cockpit-files";
    version = "39";
    src = fetchurl {
      url = "https://github.com/cockpit-project/cockpit-files/releases/download/39/cockpit-files-39.tar.xz";
      sha256 = "sha256-2YpDSqWy83/eZ39T0ICqqzJyzJIbBlQbQQdWQdT9ebM=";
    };
  };
  cockpit-podman = {
    pname = "cockpit-podman";
    version = "124";
    src = fetchurl {
      url = "https://github.com/cockpit-project/cockpit-podman/releases/download/124/cockpit-podman-124.tar.xz";
      sha256 = "sha256-g93+OH2YPF/b/llXz00DM7JiyfWpWYXEHAbgLoM6Fbo=";
    };
  };
}
