# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cockpit-files = {
    pname = "cockpit-files";
    version = "23";
    src = fetchurl {
      url = "https://github.com/cockpit-project/cockpit-files/releases/download/23/cockpit-files-23.tar.xz";
      sha256 = "sha256-6bFWSliDFUbC3+SRrhlroX0SQxgXGcns8sm8G0MYv2s=";
    };
  };
  cockpit-podman = {
    pname = "cockpit-podman";
    version = "108";
    src = fetchurl {
      url = "https://github.com/cockpit-project/cockpit-podman/releases/download/108/cockpit-podman-108.tar.xz";
      sha256 = "sha256-IIG9r43KcoStEEwCP8AHCgNy7mYS1245MRKBkfDE1e4=";
    };
  };
}
