# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  cockpit-files = {
    pname = "cockpit-files";
    version = "37";
    src = fetchurl {
      url = "https://github.com/cockpit-project/cockpit-files/releases/download/37/cockpit-files-37.tar.xz";
      sha256 = "sha256-DWc3Xs4/RgnpckS1/JuaEUYRemxI4Ii9WxTWZ/v9yz0=";
    };
  };
  cockpit-podman = {
    pname = "cockpit-podman";
    version = "122";
    src = fetchurl {
      url = "https://github.com/cockpit-project/cockpit-podman/releases/download/122/cockpit-podman-122.tar.xz";
      sha256 = "sha256-U4o5671LKoWjjMkPQIdZwymGqFt89IyTbWvOMr2c00E=";
    };
  };
}
