# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  prometheus-podman-exporter = {
    pname = "prometheus-podman-exporter";
    version = "v1.15.0";
    src = fetchFromGitHub {
      owner = "containers";
      repo = "prometheus-podman-exporter";
      rev = "v1.15.0";
      fetchSubmodules = false;
      sha256 = "sha256-eXuLiJx0WsPlPAN5ZwQIp89thXiNS6AGE9p3aqjD+K8=";
    };
  };
}
