name: Nix Flake Check
on:
  push:
  workflow_dispatch:

jobs:
  nix-flake-check:
    uses: pedorich-n/github-workflows/.github/workflows/flake-check.yaml@3a4c3b1e8d7e9e836ad87f7bfc5727c273a84a97 # main
    with:
      timeout_minutes: 20
      app_client_id: ${{ vars.APP_CLIENT_ID }}
      app_owner: ${{ github.repository_owner }}
    secrets:
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
