name: Nix Flake Check
on:
  push:
  workflow_dispatch:

jobs:
  nix-flake-check:
    uses: pedorich-n/github-workflows/.github/workflows/flake-check.yaml@rework-flows # main
    with:
      timeout_minutes: 20
    secrets:
      app_client_id: ${{ vars.APP_CLIENT_ID }}
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
