name: Nix Flake Check
on:
  push:
  workflow_dispatch:

jobs:
  nix-flake-check:
    uses: pedorich-n/github-workflows/.github/workflows/flake-check.yaml@f31e4e719947f2bfeeea9e0319414c1c1d8e11b7 # main
    with:
      timeout_minutes: 20
      app_client_id: ${{ vars.APP_CLIENT_ID }}
      app_owner: ${{ github.repository_owner }}
    secrets:
      app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
