name: Push to Nix Cache
on:
  # TODO: come up with a better trigger. Maybe only for update_flake_lock branch?
  workflow_dispatch:

jobs:
  eval-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.eval-matrix.outputs.matrix }}
    steps:
      - name: Get Github App info
        id: app_auth
        uses: pedorich-n/github-workflows/.github/actions/app-token@49b512bbb8bc337ceac27bee872950d6fa79cb2e # main
        with:
          client_id: ${{ vars.APP_CLIENT_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Setup job
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@49b512bbb8bc337ceac27bee872950d6fa79cb2e # main
        with:
          git_https_token: ${{ steps.app_auth.outputs.token }}

      - name: Evaluate matrix
        id: eval-matrix
        shell: bash
        run: |
          matrix=$(nix eval --accept-flake-config --json .#ghaMatrices.cache)
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  build-and-push:
    name: ${{ matrix.name }} (${{ matrix.system }})
    needs: eval-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJSON(needs.eval-matrix.outputs.matrix)}}
    permissions:
      contents: read
      id-token: write
    steps:
      - name: Get Github App info
        id: app_auth
        uses: pedorich-n/github-workflows/.github/actions/app-token@49b512bbb8bc337ceac27bee872950d6fa79cb2e # main
        with:
          client_id: ${{ vars.APP_CLIENT_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Setup job
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@49b512bbb8bc337ceac27bee872950d6fa79cb2e # main
        with:
          git_https_token: ${{ steps.app_auth.outputs.token }}

      - name: Setup niks3
        uses: Mic92/niks3-action@a3da573cc4d21634990e5f21391abe55ed49ec46 # v1
        with:
          server-url: ${{ vars.NIKS3_SERVER_URL }}

      - name: Build ${{ matrix.attr }}
        id: build
        shell: bash
        run: nix build --accept-flake-config --json .#"${{ matrix.attr }}"
