name: Push to Nix Cache
on:
  workflow_dispatch:
  push:

jobs:
  eval-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.eval-matrix.outputs.matrix }}
    steps:
      - name: Setup job
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@main
        with:
          git_https_token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Evaluate matrix
        id: eval-matrix
        shell: bash
        run: |
          matrix=$(nix eval --accept-flake-config --json .#ghaMatrices.cache)
          echo "matrix=$matrix" >> "$GITHUB_OUTPUT"

  build-and-push:
    name: ${{ matrix.name }} (${{ matrix.system }})
    needs: eval-matrix
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: ${{fromJSON(needs.eval-matrix.outputs.matrix)}}
    permissions:
      contents: read
      id-token: write
    env:
      NIKS3_SERVER_URL: ${{ secrets.NIKS3_SERVER_URL }}
    steps:
      - name: Setup job
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@main
        with:
          git_https_token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Build ${{ matrix.attr }}
        id: build
        shell: bash
        run: |
          build_result=$(nix build --accept-flake-config --json .#"${{ matrix.attr }}")
          out_paths=$(echo "$build_result" | jq -c '[.[].outputs.out]')
          echo "Going to push the following paths: $out_paths"

          echo "out_paths=$out_paths" >> "$GITHUB_OUTPUT"

      - name: Fetch OIDC token
        id: oidc
        shell: bash
        run: |
          set -euo pipefail

          token="$(curl -fsSL \
            -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
            "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=${NIKS3_SERVER_URL}" \
            | jq -r '.value')"
          echo "::add-mask::${token}"
          echo "token=${token}" >> "$GITHUB_OUTPUT"

      - name: Push derivations to cache
        shell: bash
        env:
          NIKS3_AUTH_TOKEN: ${{ steps.oidc.outputs.token }}
        run: |
          set -euo pipefail

          readarray -t paths < <(echo "${{ steps.build.outputs.out_paths }}" | jq -r '.[]')

          nix shell "github:Mic92/niks3#niks3" -c \
            niks3 push \
              --server-url "$NIKS3_SERVER_URL" \
              --auth-token "$NIKS3_AUTH_TOKEN" \
              "${paths[@]}"
