name: Containers Update Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 1 * *"

jobs:
  containers-update-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: nixbuild/nix-quick-install-action@v28
        with:
          load_nixConfig: false

      - name: Set up depedencies
        uses: nicknovitski/nix-develop@v1
        with:
          arguments: "./#version-updater"

      - name: Run nvchecker
        run: nvchecker -c ./containers/nvchecker.toml

      - name: Check for changes
        id: git-check
        run: |
          git diff --quiet || echo "changes_detected=true" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        if: steps.git-check.outputs.changes_detected
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GH_ACCESS_TOKEN }}
          commit-message: "Update containers"
          title: "Update containers"
          branch: "update_containers"
          labels: "automated"
