name: Update Packages' Sources

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 1 * *"

jobs:
  update-packages:
    runs-on: ubuntu-latest
    steps:
      - name: Get Github App info
        id: app_auth
        uses: pedorich-n/github-workflows/.github/actions/app-token@f32e404b915ad8006f9dac6903e30f4be78f6524 # main
        with:
          client_id: ${{ vars.APP_CLIENT_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Setup job
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@f32e404b915ad8006f9dac6903e30f4be78f6524 # main
        with:
          git_https_token: ${{ steps.app_auth.outputs.token }}

      - name: Run nix-update
        uses: pedorich-n/github-workflows/.github/actions/run-nix-update@nix-update # main
        with:
          token: ${{ steps.app_auth.outputs.token }}
          committer: ${{ steps.app_auth.outputs.committer }}
          author: ${{ steps.app_auth.outputs.committer }}
          packages: |
            error-pages
            \"cockpit-plugins.podman\"
            \"cockpit-plugins.files\"
