name: Nvfetcher Update Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 1 * *"

jobs:
  update-nvfetcher:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Setup job
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@https-instead-of-ssh
        with:
          git_https_token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Update nvfetcher sources
        run: nix run .#update-nvfetcher

      - name: Check for changes
        id: git-check
        shell: bash
        run: |
          git diff --quiet || echo "changes_detected=true" >> "$GITHUB_OUTPUT"

      - name: Create Pull Request
        if: steps.git-check.outputs.changes_detected
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          commit-message: "Update nvfetcher sources"
          title: "Update nvfetcher sources"
          branch: "update_nvfetcher"
          labels: |
            dependencies
            automated
