name: Nvfetcher Update Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 1 * *"

jobs:
  update-nvfetcher:
    runs-on: ubuntu-latest
    steps:
      - name: Setup job
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@main
        with:
          ssh_key: ${{ secrets.SSH_ACTION_KEY }}

      - name: Update nvfetcher sources
        run: nix run .#update-nvfetcher

      - name: Create PR if changes detected
        uses: ./.github/actions/pr-on-changes
        with:
          title: "Update nvfetcher sources"
          branch: "update_nvfetcher"
          token: ${{ secrets.GH_ACCESS_TOKEN }}
