name: Terraform Provider Update Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 1 * *"

jobs:
  update-terraform-providers:
    runs-on: ubuntu-latest
    steps:
      - name: Setup job
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@main
        with:
          ssh_key: ${{ secrets.ssh_key }}

      - name: Update Terraform providers
        run: nix run .#update-terraform-providers

      - name: Update terraform lock
        shell: bash
        run: |
          modules=("arr-stack" "backblaze" "tailscale")
          for module in "${modules[@]}"; do
            nix develop .#${module} --command terraform init -upgrade
          done

      - name: Create PR if changes detected
        uses: ./.github/actions/pr-on-changes
        with:
          title: "Update Terraform providers"
          branch: "update_terraform_providers"
          token: ${{ secrets.GH_ACCESS_TOKEN }}
