name: Containers Update Check

on:
  workflow_dispatch:
  schedule:
    - cron: "0 10 1 * *"

jobs:
  update-containers:
    runs-on: ubuntu-latest
    steps:
      - name: Setup job
        uses: pedorich-n/github-workflows/.github/actions/setup-nix-job@main
        with:
          ssh_key: ${{ secrets.ssh_key }}

      - name: Update containers
        run: nix run .#update-containers

      - name: Create PR if changes detected
        uses: ./.github/actions/pr-on-changes
        with:
          title: "Update containers"
          branch: "update_containers"
          token: ${{ secrets.GH_ACCESS_TOKEN }}
