[tool.poetry]
name = "systemd-onfailure-notify"
version = "0.0.0"
description = ""
authors = []
packages = [{ include = "systemd-onfailure-notify", from = "src" }]

[tool.poetry.dependencies]
python = "^3.11"
apprise = "^1.7.4"

[tool.poetry.group.dev.dependencies]
ruff = "^0.3.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
systemd-onfailure-notify = "systemd-onfailure-notify.main:main"

[tool.ruff]
line-length = 140
target-version = "py311"

[tool.ruff.lint]
extend-select = ["I"]